### ISSUE TITLE
怎么说不出话来了

### ISSUE THREAD

**Issue by kirbystudy** [wuuconix/live2d-cdn#1]

**Comment by wuuconix** [comment]
https://wuuconix.github.io/live2d-cdn/
请刷新缓存后尝试以上演示页面。
我尝试了一下，能够说话，但是有一定延迟。
jsDeliver最近貌似越来越慢了。
音频wav文件的传输可能比较慢。

**Comment by kirbystudy** [comment]
好的，我可以用你的模型放在线上吗，我会标注作者的

**Comment by wuuconix** [comment]
你可以在任何地方自由使用此项目。
这个小埋模型我也是从[其他仓库](https://github.com/imuncle/live2d)copy过来的。
不标注也行，如果标注的话，我会感谢你。
