### ISSUE TITLE
可以导入自己的模型吗，需要改那些参数。

### ISSUE THREAD

**Issue by kirbystudy** [wuuconix/live2d-cdn#3]

**Comment by wuuconix** [comment]
可以修改，删除 [model](https://github.com/wuuconix/live2d-cdn/tree/main/model)文件夹中原本的小埋模型。
然后导入一个新的模型。导入后修改[model_list.json](https://github.com/wuuconix/live2d-cdn/blob/main/model_list.json)文件。
最后为了更好的体验，修改这个参数为你新的模型的texture的url链接
https://github.com/wuuconix/live2d-cdn/blob/ad1fe8b60e861ecd3740b29d05b0bd05a352f360/autoload.js#L2

**Comment by kirbystudy** [comment]
只能单个模型吗，没弄多人模型?

**Comment by wuuconix** [comment]
可以多模型，但是我没这方面需求。
本仓库只提供小埋模型，请自行添加。
model_list.json多加几个就行了。
请参考这个仓库：
https://github.com/fghrsh/live2d_api/blob/master/model_list.json
waifu-tools我把换模型的按钮删掉了，请换成这样的启用。
https://github.com/stevenjoezhang/live2d-widget/blob/ae27493c29391e0cf2e9c08d27ab9d466f0a9c93/autoload.js#L39
